"""The HTTP surface: the Talk webhook, the alerting endpoint, and a health check.

Routes
------
``POST /webhook``  Nextcloud Talk posts events here. Signature-verified, then
                   handled in the background so we answer well inside Talk's
                   request timeout.
``POST /notify``   Inbound alerting: other systems post JSON here with a bearer
                   token and we relay it into a conversation.
``GET  /healthz``  Liveness probe.
"""

from __future__ import annotations

import asyncio
import hmac
import json
import logging
import re
from contextlib import asynccontextmanager
from typing import Annotated, AsyncIterator

import httpx
from fastapi import FastAPI, Header, HTTPException, Request, Response, status
from pydantic import BaseModel, Field

from . import __version__
from .bot import Bot
from .config import Config
from .events import EventError, parse_event
from .signing import HEADER_BACKEND, HEADER_RANDOM, HEADER_SIGNATURE, verify
from .talk import TalkError

log = logging.getLogger(__name__)

#: Talk conversation tokens as generated by Nextcloud.
TOKEN_RE = re.compile(r"^[A-Za-z0-9]{4,64}$")

#: How long shutdown waits for in-flight replies to finish.
DRAIN_TIMEOUT = 30.0


class NotifyRequest(BaseModel):
    """An alert to relay into a conversation."""

    room: str = Field(min_length=1, description="Conversation token, or an alias from SABLE_NOTIFY_ROOMS")
    message: str = Field(min_length=1, description="Markdown message body")
    silent: bool = Field(default=False, description="Post without triggering notifications")
    reply_to: int = Field(default=0, ge=0, alias="replyTo", description="Message id to reply to")

    model_config = {"populate_by_name": True}


def create_app(config: Config | None = None, bot: Bot | None = None) -> FastAPI:
    """Build the ASGI app. Pass ``config``/``bot`` in tests; otherwise read the env."""
    config = config or (bot.config if bot else Config.from_env())
    tasks: set[asyncio.Task[None]] = set()

    @asynccontextmanager
    async def lifespan(app: FastAPI) -> AsyncIterator[None]:
        app.state.bot = bot or Bot(config)

        # What is running, and with what. An operator reading only the first
        # dozen lines of the log should be able to tell whether the thing is
        # configured the way they meant.
        log.info("sable %s starting", __version__)
        log.info("  listening on:   http://%s:%s", config.host, config.port)
        log.info("  webhook URL:    POST /webhook  (give this to occ talk:bot:install)")
        log.info(
            "  nextcloud:      %s",
            config.nextcloud_url or "(taken from each signed webhook)",
        )
        log.info(
            "  bot name:       %r   command prefix: %r",
            config.bot_name,
            config.command_prefix,
        )
        log.info(
            "  model:          %s",
            f"{config.llm.model} at {config.llm.base_url}" if config.llm.enabled else "disabled",
        )
        log.info(
            "  ask reaction:   %s",
            config.ask_reaction or "disabled",
        )
        log.info(
            "  ai rooms:       %s",
            ", ".join(config.ai_rooms) if config.ai_rooms else "(mentions only)",
        )
        log.info(
            "  alerting:       %s",
            f"enabled, aliases: {', '.join(config.notify_rooms)}"
            if config.notify_enabled and config.notify_rooms
            else ("enabled" if config.notify_enabled else "disabled (/notify answers 404)"),
        )
        log.info("  backend pin:    %s", "on" if config.pin_backend else "off")
        log.info("  log level:      %s", config.log_level)

        if config.startup_check:
            await app.state.bot.check_nextcloud()

        log.info("sable %s ready", __version__)
        try:
            yield
        finally:
            log.info("sable %s stopping", __version__)
            if tasks:
                log.info("waiting for %d in-flight reply/replies", len(tasks))
                await asyncio.wait(tasks, timeout=DRAIN_TIMEOUT)
            if bot is None:
                await app.state.bot.aclose()
            log.info("sable %s stopped", __version__)

    app = FastAPI(
        title="sable",
        version=__version__,
        description="A Nextcloud Talk bot.",
        lifespan=lifespan,
    )

    def spawn(coro) -> None:
        """Run a handler detached from the request, keeping a strong reference."""
        task = asyncio.create_task(coro)
        tasks.add(task)
        task.add_done_callback(tasks.discard)
        task.add_done_callback(_log_task_failure)

    def current_bot(request: Request) -> Bot:
        """The Bot built during startup. Read from app.state rather than through
        Depends: a locally defined alias is not resolvable under postponed
        annotations, and FastAPI would take it for a query parameter."""
        return request.app.state.bot

    @app.get("/healthz", tags=["ops"])
    async def healthz() -> dict[str, object]:
        return {
            "status": "ok",
            "version": __version__,
            "bot": config.bot_name,
            "llm": config.llm.model or None,
            "notify": config.notify_enabled,
        }

    @app.post("/webhook", status_code=status.HTTP_200_OK, tags=["talk"])
    async def webhook(
        request: Request,
        signature: Annotated[str, Header(alias=HEADER_SIGNATURE)] = "",
        random: Annotated[str, Header(alias=HEADER_RANDOM)] = "",
        backend: Annotated[str, Header(alias=HEADER_BACKEND)] = "",
    ) -> dict[str, str]:
        body = await request.body()

        if not verify(random, signature, body, config.bot_secret):
            log.warning("rejected a webhook with a bad signature from %s", backend or "?")
            raise HTTPException(status.HTTP_401_UNAUTHORIZED, "invalid signature")

        backend = backend.rstrip("/")
        if config.pin_backend and backend != config.nextcloud_url:
            log.error(
                "rejected a webhook claiming backend %r; expected %r",
                backend,
                config.nextcloud_url,
            )
            raise HTTPException(status.HTTP_403_FORBIDDEN, "unexpected backend")

        try:
            payload = json.loads(body)
        except json.JSONDecodeError as exc:
            raise HTTPException(status.HTTP_400_BAD_REQUEST, f"invalid JSON: {exc}") from exc

        try:
            event = parse_event(payload, backend=backend)
        except EventError as exc:
            log.warning("unparseable event: %s", exc)
            raise HTTPException(status.HTTP_400_BAD_REQUEST, str(exc)) from exc

        log.debug(
            "accepted %s from %s in %s (message %s)",
            event.type,
            event.actor.id or "?",
            event.room_token,
            event.message_id or "-",
        )
        # Answer now, work later: a model call can take longer than Talk waits.
        spawn(current_bot(request).handle(event))
        return {"status": "accepted"}

    @app.post("/notify", status_code=status.HTTP_201_CREATED, tags=["alerting"])
    async def notify(
        request: Request,
        payload: NotifyRequest,
        authorization: Annotated[str, Header()] = "",
    ) -> dict[str, object]:
        if not config.notify_enabled:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "alerting endpoint is disabled")
        _check_bearer(authorization, config.notify_token)

        room = config.notify_rooms.get(payload.room, payload.room)
        if not TOKEN_RE.match(room):
            raise HTTPException(
                status.HTTP_400_BAD_REQUEST,
                f"{payload.room!r} is not a known alias or a valid conversation token",
            )

        try:
            message_id = await current_bot(request).send(
                room, payload.message, silent=payload.silent, reply_to=payload.reply_to
            )
        except TalkError as exc:
            log.warning("relaying an alert to %s failed: %s", room, exc)
            # 404/400 from Talk is the caller's problem; anything else is ours.
            code = (
                status.HTTP_400_BAD_REQUEST
                if exc.status in {400, 404}
                else status.HTTP_502_BAD_GATEWAY
            )
            raise HTTPException(code, f"Talk rejected the message: {exc}") from exc
        except httpx.HTTPError as exc:
            raise HTTPException(
                status.HTTP_502_BAD_GATEWAY, f"could not reach Nextcloud: {exc}"
            ) from exc

        log.info(
            "relayed an alert to %s%s as message %s",
            room,
            f" (alias {payload.room})" if payload.room != room else "",
            message_id or "?",
        )
        return {"ok": True, "room": room, "messageId": message_id}

    @app.get("/", include_in_schema=False)
    async def root() -> Response:
        return Response(f"sable {__version__}\n", media_type="text/plain")

    return app


def _check_bearer(header: str, expected: str) -> None:
    scheme, _, token = header.partition(" ")
    if scheme.lower() != "bearer" or not hmac.compare_digest(token.strip(), expected):
        raise HTTPException(
            status.HTTP_401_UNAUTHORIZED,
            "a valid bearer token is required",
            headers={"WWW-Authenticate": "Bearer"},
        )


def _log_task_failure(task: asyncio.Task[None]) -> None:
    if task.cancelled():
        return
    exc = task.exception()
    if exc is not None:
        log.error("handling an event failed", exc_info=exc)
